### ISSUE TITLE
mysql root passwd not login

### ISSUE THREAD

**Issue by txg1550759** [youdowell/k8s-galera-init#1]
[root@master3 mariadb-cluster]# cat mysql-secrets.yaml

```
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: galera
  labels:
    app: mysql
data:
  # Root password: changeit run  echo idea77|base64
  root-password: YWRtaW4K
  # Root user: root
  root-user: cm9vdA==
```

[root@master3 mariadb-cluster]# echo admin|base64

`YWRtaW4K`

[root@master3 setateful-set-mysql]# kubectl get pod --namespace=galera -o wide

```
NAME      READY     STATUS    RESTARTS   AGE       IP           NODE
mysql-0   1/1       Running   0          3m        172.1.56.4   192.168.1.69
mysql-1   1/1       Running   1          2m        172.1.49.6   192.168.2.69
mysql-2   0/1       Running   0          39s       172.1.98.2   192.168.2.68
```

[root@master3 setateful-set-mysql]# kubectl exec -it --namespace=galera mysql-0 /bin/bash

```
root@mysql-0:/# echo $MYSQL_ROOT_PASSWORD
admin
root@mysql-0:/# mysql -uroot -padmin
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@mysql-0:/#
```
