### ISSUE TITLE
some mysql errors log

### ISSUE THREAD

**Issue by seecsea** [youdowell/k8s-galera-init#2]
kubectl logs mysql-0
2017-06-07  2:57:39 140272615787264 [ERROR] Invalid (old?) table or database name 'lost+found'

**Comment by seecsea** [comment]
[root@localhost:/opt/dockerfile/galera/galera]# chmod 755 on-start.sh
rebuild and ok,thanks.

**Comment by ausov** [comment]
Yep, seems hitting the old issue with mysql/mariadb. When mapped to root of a device, some system folders are interpreted as DBs.

Solutions:

* move mysql data dir to any subdir of the root folder of the mounted device
* add `ignore-db-dir=lost+found` to my.cnf

I will update the repo with the fix also. Thank you!

**Comment by seecsea** [comment]
add one line:         
subPath: mysql
and the error logs gone
      
```yaml
  - name: data
     mountPath: /var/lib/mysql
     subPath: mysql      #this line just not to create the lost+found folder of the mounted device
      volumes:
      - name: config
        configMap:
          name: mysql-config-vol
      imagePullSecrets:
      - name: registrykey-andy
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: defalut-rbd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
```
